//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCHelper2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCHelper2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;items&gt;
        /// &lt;topic0&gt;CLICK HERE TO ADD&lt;/topic0&gt;
        ///WELCOME KIET!
        ///&lt;/topic0&gt;
        /// &lt;topic1&gt;&lt;/topic1&gt;
        /// &lt;topic2&gt;&lt;/topic2&gt;
        /// &lt;topic3&gt;&lt;/topic3&gt;
        /// &lt;topic4&gt;&lt;/topic4&gt;
        /// &lt;topic5&gt;&lt;/topic5&gt;
        /// &lt;host1&gt;STEPH MORRISON&lt;/host1&gt;
        /// &lt;host2&gt;EVAN MORRISON&lt;/host2&gt;
        /// &lt;host3&gt;TY TREMBLAY&lt;/host3&gt;
        /// &lt;host4&gt;DAVID McLAUGHLIN&lt;/host4&gt;
        /// &lt;guest1&gt;FRANCIS O&apos;ROURKE&lt;/guest1&gt;
        /// &lt;guest2&gt;NAVID SHAFA&lt;/guest2&gt;
        /// &lt;question&gt;Have a question? Tweet: @FRCGameSense #FRCGS | Email: gamesense@frcgamesense.com | Chat: “!q” in Twitch and YouTube&lt;/question&gt;
        /// &lt;author [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string streamcontrol {
            get {
                return ResourceManager.GetString("streamcontrol", resourceCulture);
            }
        }
    }
}
